flintwiki
moja-global/moja_global_docs pull request #145
Opened 2021-11-03 14:47 UTC by MercybirungiS

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- [ ] Issue reference: 
- [ ] Subject Matter Expert (SME) reviewer: 
- [ ] Peer reviewer: 
- [ ] Preview Links: 
- [ ] Explain the changes: 
- [ ] Dependency changes: 

Thanks for opening the Pull Request for moja global. Happy contributing ✨

2021-11-03 15:16 UTC, MercybirungiS commented
I added the wiki docs to the moja global docs that are version controlled.

2021-11-04 12:09 UTC, HarshCasper requested changes
Hi @MercybirungiS 

The work is not completely correct. We would not like to add FLINT as a submodule but migrate the FLINT Wiki to the specific doc pages that I had shared with you.

You might want to convert those Markdown pages to RST and put them here.

2021-11-04 12:23 UTC, MercybirungiS commented
okay let me work on that

2021-11-05 06:28 UTC, HarshCasper requested changes
Review Round-1

2021-11-05 06:28 UTC, HarshCasper commented on .gitmodules
> +	url = https://github.com/moja-global/FLINT.git
Please remove this (delete the file)

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.-Moja-FLINT.rst
> +**Welcome to the Full Land Integration Tool!**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/Home.rst
> +Welcome to the moja.global wiki!
You can delete this

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/3.4-Module-Science.rst
> +**Empirical Growth Model**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/3.4-Module-Science.rst
> +**Hybrid forest growth**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/3.4-Module-Science.rst
> +capacity\|
The tables are not rendered correctly

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/3.4-Module-Science.rst
> +temperature\| 8. Minimum temperature\| 9. Global radiation\|
The tables are not rendered correctly

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/3.4-Module-Science.rst
> +| 12. Depth of soil layer sampled. \|
The tables are not rendered correctly

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.1-Pools.rst
> +**What is a pool?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.1-Pools.rst
> +**How are pools used in FLINT?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.2-Operations.rst
> +**What is an operation?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.2-Operations.rst
> +**How are operations used in FLINT?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.3-Module.rst
> +**What is a module?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.3-Module.rst
> +**How do modules operate?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.3-Module.rst
> +**Modules for disturbance events**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.3-Module.rst
> +**Carbon pool events**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.4-Simulation-Units.rst
> +**What is a Simulation Unit?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/1.4-Simulation-Units.rst
> +**How are Simulation Units used in the FLINT?**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/2.-Data-Preparation.rst
> +**NoSQL Database**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/2.-Data-Preparation.rst
> +**Vector**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/2.-Data-Preparation.rst
> +**Data Provider types**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/2.-Data-Preparation.rst
> +**Input data from the FLINT**
Use a proper heading here

2021-11-05 06:28 UTC, HarshCasper commented on docs/FLINT.wiki/2.-Data-Preparation.rst
> +**Types of data**
Use a proper heading here

2021-12-12 07:53 UTC, HarshCasper requested changes
The docs are not referenced anywhere across the website. I will close this PR in favor of a different one.

2021-12-12 07:53 UTC, closed without merging