DOCS: Host python notebooks containing different data types using MyST-NB
moja-global/moja_global_docs pull request #178
Opened 2022-05-04 13:57 UTC by derha

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- [ ] Issue reference: https://github.com/moja-global/moja_global_docs/issues/161
- [ ] Subject Matter Expert (SME) reviewer: 
- [ ] Peer reviewer: 
- [ ] Preview Links: 
- [ ] Explain the changes: The Jupyter Notebooks made by @padmajabhol that investigate FLINT data types were parsed and hosted on documentation website.
- [ ] Dependency changes: Yes, sphinx MyST-NB extension for compiling Jupyter Notebooks was used.

Thanks for opening the Pull Request for moja global. Happy contributing ✨

2022-05-06 06:30 UTC, padmajabhol commented
There are a few issues with the notebooks from my end. Will correct them. All the checks have passed,  thanks a lot @derha !

2022-05-06 06:52 UTC, Namyalg commented
Yes, as the pandoc issue is resolved, we can go ahead with this

2022-05-06 13:26 UTC, derha commented
I'm glad I could help!

2022-05-06 15:55 UTC, padmajabhol requested changes

2022-05-06 15:55 UTC, padmajabhol commented on docs/Understanding-FLINT/FLINT-Inputs/index.rst
> +We currently use five main data-types that are used as FLINT inputs - geoTIFF, JSON, CSV, SQL DB, Shapefile. We have hosted the python notebooks for each data type that contains the instructions and
Replace line 4 with : We currently have five main data types used as FLINT inputs - geoTIFF, JSON, CSV, SQL DB, and Shapefile. Final change and the PR is good to go! 🚀

2022-05-06 18:58 UTC, padmajabhol approved these changes

2022-05-06 23:40 UTC, aornugent commented
Thanks @derha!

@padmajabhol, I think you have permissions to merge in docs repositories?  🤞

2022-05-07 04:15 UTC, padmajabhol commented
> Thanks @derha!
> 
> @padmajabhol, I think you have permissions to merge in docs repositories? 🤞

Yes!

2022-05-07 04:15 UTC, merged