schema representation for tables input database
moja-global/moja_global_docs pull request #179
Opened 2022-05-08 04:27 UTC by Namyalg

# Description

This PR creates the sample schema representation of the tables present in the input database

- [X] Subject Matter Expert (SME) reviewer: @aornugent 
- [X] Peer reviewer: @padmajabhol 
- [ ] Preview Links: 
- [X] Explain the changes: 

Thanks for opening the Pull Request for moja global. Happy contributing ✨

2022-05-11 17:13 UTC, Namyalg commented
> The linkcheck build is failing due to an external link that takes too long to load. I have added an option to ignore it in my PR: [5cead6c](https://github.com/moja-global/moja_global_docs/commit/5cead6c711c003101db0a031e9857f955f3ad98a) Maybe you can do the same? This should ideally go in the same folder as the notebooks in PR #180 since the schemas are involved in the GCBM simulation.

Thank for pointing it out, it is fixed now

2022-05-16 12:44 UTC, padmajabhol requested changes
You can move this into [INvestigating the GCBM Inputs](https://docs.moja.global/en/latest/Understanding-FLINT/GCBM-Inputs/InvestigatingGCBM-Inputs/index.html).

2022-05-16 13:42 UTC, Namyalg commented
Done @padmajabhol

2022-05-16 15:34 UTC, padmajabhol approved these changes

2022-05-16 15:35 UTC, merged